version: '3.7'
services:
  app:
    container_name: holymoly
    image: foxxravin/holymoly:holymoly-v0.1.1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

    tty: true
    stdin_open: true
    command: poetry run pytest
