name: ci

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # docker compose
      - name: Tests
        # build and assert on error
        run: docker-compose up --build --abort-on-container-exit

  assertin:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assert
        run: |
          echo "Asserting..."
  # push_to_registry:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Push to Docker Hub
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
