name: ci

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # docker compose
      - name: Tests
        run: docker-compose up --build --abort-on-container-exit

  assert:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assert
        run: echo "Asserting..."
