name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # docker compose
      - name: docker-compose up
        uses: docker/build-push-action@v2
        with:
          run: docker-compose up -d

      # if run without error build and push to docker hub
      - name: Build and push
        if: ${{ success() }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-compose-action:${{ github.sha }}
          cache-from: type=registry,ref=$DOCKER_USERNAME/docker-compose-action:cache
          cache-to: type=registry,ref=$DOCKER_USERNAME/docker-compose-action:cache,mode=max
