name: ci

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # docker compose
      - name: Tests
        # build and assert on error
        run: docker-compose up --build --abort-on-container-exit

  push_to_registry:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Push
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: docker-compose push
